import React, {Component} from 'react';
import {Dropdown} from 'primereact/dropdown';
export default class DropdownClass extends Component {

    constructor() {
        super();
        this.state = {
            vantagem: null, 
           desvantagem: null
        };
        
        this.onVantagemChange = this.onVantagemChange.bind(this);
        this.onDesvantagemChange = this.onDesvantagemChange.bind(this);
        
    }

    onVantagemChange(e) {
        this.setState({vantagem: e.value});
    }
    onDesvantagemChange(e) {
        this.setState({desvantagem: e.value});
    }

   
    render() {
        const vantagens = [
            {name: 'Aceleração (1 pto)', code: 'Aceleração'},
            {name: 'Adaptador (1 pto)', code: 'Adaptador'},
            {name: 'Aliado (1 pto)', code: 'Aliado'},
            {name: 'Alma Pura (0 pto)', code: 'Alma Pura'},
            {name: 'Alvos Múltiplos (2 pto)', code: 'Alvos Múltiplos'},
            {name: 'Ambidestro (0 pto)', code: 'Ambidestro'},
            {name: 'Anão (2 pto)', code: 'Anão'},
            {name: 'Aparencia Inofensiva (1 pto)', code: 'Aparencia Inofensiva'},
            {name: 'Arcano (4 pto)', code: 'Arcano'},
            {name: 'Area de Batalha (2 pto)', code: 'Area de Batalha'},
            {name: 'Arena (1 pto)', code: 'Arena'},
            {name: 'Arma Especial (1 pto)', code: 'Arma Especial'},
            {name: 'Armadura Extra poder de fogo (4 pto)', code: 'Armadura Extra poder de fogo'},
            {name: 'Armadura Extra força (3 pto)', code: 'Armadura Extra força'},
            {name: 'Armadura Extra magia (3 pto)', code: 'Armadura Extra magia'},
            {name: 'Armadura Extra corte (2 pto)', code: 'Armadura Extra corte'},
            {name: 'Armadura Extra perfuração (2 pto)', code: 'Armadura Extra perfuração'},
            {name: 'Armadura Extra contusão (2 pto)', code: 'Armadura Extra contusão'},
            {name: 'Armadura Extra explosão (2 pto)', code: 'Armadura Extra explosão'},
            {name: 'Armadura Extra calor/fogo (2 pto)', code: 'Armadura Extra calor/fogo'},
            {name: 'Armadura Extra frio/gelo (2 pto)', code: 'Armadura Extra frio/gelo'},
            {name: 'Armadura Extra eletrecidade (2 pto)', code: 'Armadura Extra eletrecidade'},
            {name: 'Armadura Extra Veneno (2 pto)', code: 'Armadura Extra Veneno'},
            {name: 'Armadura Extra vento/som (2 pto)', code: 'Armadura Extra vento/som'},
            {name: 'Armadura Extra quimicos (2 pto)', code: 'Armadura Extra quimicos'},
            {name: 'Armadura Extra acido (2 pto)', code: 'Armadura Extra acido'},
            {name: 'Armadura Extra agua (2 pto)', code: 'Armadura Extra agua'},
            {name: 'Armadura Extra liquidos (4 pto)', code: 'Armadura Extra liquidos'},
            {name: 'Artifice de vida (4 pto)', code: 'Artifice de vida'},
            {name: 'Ataque Especial (AE) (1 pto)', code: 'Ataque Especial'},
            {name: 'Ataque Especial area (AE +3 pto)', code: 'Ataque Especial area'},
            {name: 'Ataque Especial paralisante (AE +1 pto)', code: 'Ataque Especial paralisante'},
            {name: 'Ataque Especial preciso (AE +1 pto)', code: 'Ataque Especial preciso'},
            {name: 'Ataque Especial teleguiado (AE +1 pto)', code: 'Ataque Especial teleguiado'},
            {name: 'Ataque Especial lento (AE -1 pto)', code: 'Ataque Especial lento'},
            {name: 'Ataque Especial perto de morte (AE -2 pto)', code: 'Ataque Especial perto de morte'},
            {name: 'Ataque multiplo (1 pto)', code: 'Ataque multiplo'},
            {name: 'Ataque multiplo a distância (2 pto)', code: 'Ataque multiplo a distância'},
            {name: 'Bárbaro* (2 pto)', code: 'Bárbaro*'},
            {name: 'Bardo* (2 pto)', code: 'Bardo*'},
            {name: 'Boa fama (1 pto)', code: 'Boa fama'},
            {name: 'Bomba Relógio (0 pto)', code: 'Bomba Relógio'},
            {name: 'Bom Senso (1 pto)', code: 'Bom Senso'},
            {name: 'Caçador de Dragões* (4 pto)', code: 'Caçador de Dragões*'},
            {name: 'Canto do Canário (2-4 pto)', code: 'Canto do Canário'},
            {name: 'Captação (1 pto)', code: 'Captação'},
            {name: 'Carisma (1 pto)', code: 'Carisma'},
            {name: 'Cavaleiro* (3 pto)', code: 'Cavaleiro'},
            {name: 'Centauro* (2 pto)', code: 'Centauro*'},
            {name: 'Ceratop* (1 pto)', code: 'Ceratop*'},
            {name: 'Centauro élfico* (4 pto)', code: 'Centauro élfico'},
            {name: 'Clericato (2 pto)', code: 'Clericato'},
            {name: 'Comida, Sono e Ar Anulados (1 pto)', code: 'Comida, Sono e Ar Anulados'},
            {name: 'Controlar Máquinas (2 pto)', code: 'Controlar Máquinas'},
            {name: 'Construtor (0 pto)', code: 'Construtor'},
            {name: 'Coragem (0 pto)', code: 'Coragem'},
            {name: 'Corpo Corrosivo (2 pto)', code: 'Corpo Corrosivo'},
            {name: 'Corpo Arenoso (2 pto)', code: 'Corpo Arenoso'},
            {name: 'Corpo Flamejante ou Lava (3 pto)', code: 'Corpo Flamejante ou Lava'},
            {name: 'Corpo Gasoso (2 pto)', code: 'Corpo Gasoso'},
            {name: 'Corpo Líquido (3 pto)', code: 'Corpo Líquido'},
            {name: 'Corpo Metálico / Rochoso (5 pto)', code: 'Corpo Metálico / Rochoso'},
            {name: 'Dano Gigante (3 pto)', code: 'Dano Gigante'},
            {name: 'Deflexão (1 pto)', code: 'Deflexão'},
            {name: 'Domador de Feras (3 pto)', code: 'Domador de Feras'},
            {name: 'Dragoas Caçadoras* (1 pto)', code: 'Dragoas Caçadoras'},
            {name: 'Duro de Matar (0 pto)', code: 'Duro de Matar'},
            {name: 'Energia Extra (2 pto)', code: 'Energia Extra'},
            {name: 'Elfo* (2 pto)', code: 'Elfo*'},
            {name: 'Energia extra perto da morte (1 pto)', code: 'Energia extra perto da morte'},
            {name: 'Energia Vital (2 pto)', code: 'Energia Vital'},
            {name: 'Entender Tecnologia (1 pto)', code: 'Entender Tecnologia'},
            {name: 'Etherismo (1 pto)', code: 'Etherismo'},
            {name: 'Fada* (4 pto)', code: 'Fada*'},
            {name: 'Familiar (1 pto)', code: 'Familiar'},
            {name: 'Fantasma* (4 pto)', code: 'Fantasma*'},
            {name: 'Ferramentas (1 pto)', code: 'Ferramentas'},
            {name: 'Flecha Arcana (1 pto)', code: 'Flecha Arcana'},
            {name: 'Foco em Arma (0 pto)', code: 'Foco em Arma'},
            {name: 'Foco em Magia (0-1 pto)', code: 'Foco em Magia'},
            {name: 'Foco em Pericia (0 pto)', code: 'Foco em Pericia'},
            {name: 'Forma Alternativa (2-4 pto)', code: 'Forma Alternativa'},
            {name: 'Genialidade (-1 pto)', code: 'Genialidade'},
            {name: 'Gladiador* (1 pto)', code: 'Gladiador*'},
            {name: 'Gnomo* (1 pto)', code: 'Gnomo*'},
            {name: 'Golpe Furioso (2 pto)', code: 'Golpe Furioso'},
            {name: 'Halfling* (1 pto)', code: 'Halfling*'},
            {name: 'Hobgoblin* (1 pto)', code: 'Hobgoblin*'},
            {name: 'Homúnculo* (1 pto)', code: 'Homúnculo*'},
            {name: 'Idade Imutável (0 pto)', code: 'Idade Imutável'},
            {name: 'Imortal* (1 pto)', code: 'Imortal*'},
            {name: 'Implantes (variável)', code: 'Implantes'},
            {name: 'Imunidade (1 pto)', code: 'Imunidade'},
            {name: 'Iniciativa Aprimorada (1 pto)', code: 'Iniciativa Aprimorada'},
            {name: 'Inimigo Favorito (1 pto)', code: 'Inimigo Favorito'},
            {name: 'Intangível (4 pto)', code: 'Intangível'},
            {name: 'Invisibilidade (2 pto)', code: 'Invisibilidade'},
            {name: 'Lança-Arpão (0 pto)', code: 'Lança-Arpão'},
            {name: 'Levitação (2 pto)', code: 'Levitação'},
            {name: 'Licantropo* (0 pto)', code: 'Licantropo*'},
            {name: 'Lich* (especial)', code: 'Lich*'},
            {name: 'Ligação Natural (1 pto)', code: 'Ligação Natural'},
            {name: 'Lince (1-2 pto)', code: 'Lince'},
            {name: 'Longevidade (0 pto)', code: 'Longevidade'},
            {name: 'Maquina (2 pto)', code: 'Maquina'},
            {name: 'Magia Silenciosa (1 pto)', code: 'Magia Silenciosa'},
            {name: 'Mago Especialista* (0 pto)', code: 'ana'},
            {name: 'Marujo* (0 pto)', code: 'Marujo*'},
            {name: 'Mascote (0 pto)', code: 'Mascote'},
            {name: 'Meio Dragão* (12 pto)', code: 'Meio Dragão*'},
            {name: 'Meio Elfo* (1 pto)', code: 'Meio Elfo *'},
            {name: 'Meio Metaliano* (2 pto)', code: 'Meio Metaliano*'},
            {name: 'Membro Coletor (0 pto)', code: 'Membro Coletor'},
            {name: 'Membros Elásticos (1 pto)', code: 'Membros Elásticos'},
            {name: 'Membros extras (3 pto)', code: 'Membros extras'},
            {name: 'Memoria Expandida (2 pto)', code: 'Memoria Expandida'},
            {name: 'Mente Repartilhada (2 pto)', code: 'Mente Repartilhada'},
            {name: 'Mestre (1 pto)', code: 'Mestre'},
            {name: 'Necromante* (1 pto)', code: 'Necromante*'},
            {name: 'Ninja* (3 pto)', code: 'Ninja*'},
            {name: 'Modelagem (2 pto)', code: 'Modelagem'},
            {name: 'Mutilação (0-1 pto)', code: 'Mutilação'},
            {name: 'Ocultismo (2 pto)', code: 'Ocultismo'},
            {name: 'Oráculo (1 pto)', code: 'Oráculo'},
            {name: 'Orda (0 pto)', code: 'Orda'},
            {name: 'Paralisia (1 pto)', code: 'Paralisia'},
            {name: 'Parceiro (1-2 pto)', code: 'Parceiro'},
            {name: 'Patrono (2 pto)', code: 'Patrono'},
            {name: 'Patrulheiro Selvagem (3 pto)', code: 'Patrulheiro Selvagem'},
            {name: 'Perito (1 pto)', code: 'Perito'},
            {name: 'Piratas (0-4 pto)', code: 'Piratas'},
            {name: 'Poder Oculto (1-5 pto)', code: 'Poder Oculto'},
            {name: 'Pontos de Magia Extra (1 pto)', code: 'Pontos de Magia Extra'},
            {name: 'Pontos de Vida Extra (1 pto)', code: 'Pontos de Vida Extra'},
            {name: 'Possessão (2 pto)', code: 'Possessão'},
            {name: 'Pulso Eletromagnético (1 pto)', code: 'Pulso Eletromagnético'},
            {name: 'Predestinado (1 pto)', code: 'Predestinado'},
            {name: 'Ptero* (0 pto)', code: 'Ptero*'},
            {name: 'Redenção (1 pto)', code: 'Redenção'},
            {name: 'Reflexão (2 pto)', code: 'Reflexão'},
            {name: 'Regeneração (3 pto)', code: 'Regeneração'},
            {name: 'Resistência a magia (1 pto)', code: 'Resistência a magia'},
            {name: 'Riqueza (3 pto)', code: 'Riqueza'},
            {name: 'Salto (1 pto)', code: 'Salto'},
            {name: 'Samurai (4 pto)', code: 'Samurai'},
            {name: 'Secundar (2 pto)', code: 'Secundar'},
            {name: 'Sem Armas (0 pto)', code: 'Sem Armas'},
            {name: 'Sentido especial: Audição aguçada (1 pto)', code: 'Sentido especial: Audição aguçada'},
            {name: 'Sentido especial: Faro Aguçado (1 pto)', code: 'Sentido especial: Faro Aguçado'},
            {name: 'Sentido especial: Infravisão (1 pto)', code: 'Sentido especial: Infravisão'},
            {name: 'Sentido especial: Radar (1 pto)', code: 'Sentido especial: Radar'},
            {name: 'Sentido especial: Ver o invisel (1 pto)', code: 'Sentido especial: Ver o invisel'},
            {name: 'Sentido especial: Visão aguçada (1 pto)', code: 'Sentido especial: Visão aguçada'},
            {name: 'Sentido especial: Visão de raio X (1 pto)', code: 'Sentido especial: Visão de raio x'},
            {name: 'Sentidos especiais: Todos (2 pto)', code: 'Sentidos especiais: Todos'},
            {name: 'Separação (clones) (2 pto)', code: 'Separação (clones)'},
            {name: 'Sexto Sentido (1-2 pto)', code: 'Sexto Sentido'},
            {name: 'Sorte Exagerada (1 pto)', code: 'Sorte Exagerada'},
            {name: 'Status (0-1 pto)', code: 'Status'},
            {name: 'Superpoder (focus)', code: 'Superpoder'},
            {name: 'Super Escudo (1 pto)', code: 'Super Escudo'},
            {name: 'Super Força (1 pto)', code: 'Super Força'},
            {name: 'Tauro (0 pto)', code: 'Tauro'},
            {name: 'Telecinese (2 pto)', code: 'Telecinese'},
            {name: 'Telepatia (2 pto)', code: 'Telepatia'},
            {name: 'Teleporte (2 pto)', code: 'Teleporte'},
            {name: 'Terreno (1 pto)', code: 'Terreno'},
            {name: 'Tiro Contínuo (0 pto)', code: 'Tiro Contínuo'},
            {name: 'Tiro Carregavel (2 pto)', code: 'Tiro Carregavel'},
            {name: 'Tiro Multiplo (2 pto)', code: 'Tiro Multiplo'},
            {name: 'Toque de energia (1 pto)', code: 'Toque de energia'},
            {name: 'Torcida (1 pto)', code: 'Torcida'},
            {name: 'Transfigurar (2-3 pto)', code: 'Transfigurar'},
            {name: 'Transporte (0 pto)', code: 'Transporte'},
            {name: 'Troglodita* (3 pto)', code: 'Troglodita*'},
            {name: 'Vácuo (0 pto)', code: 'Vácuo'},
            {name: 'Velocis* (0 pto)', code: 'Velocis*'},
            {name: 'Wu Jen* (0 pto)', code: 'Wu Jen*'}
        ];
        const desvantagens = [
            {name: 'Alergia (-1 pto)', code: 'Alergia'},
            {name: 'Acromatopsia (-1 pto)', code: 'Acromatopsia'},
            {name: 'Alimentação Bizarra (-1 pto)', code: 'Alimentação Bizarra'},
            {name: 'Ambiente Especial (-1 pto)', code: 'Ambiente Especial'},
            {name: 'Armadura Extra dor (-2 pto)', code: 'Armadura Extra dor'},
            {name: 'Assombrado (-2 pto)', code: 'Assombrado'},
            {name: 'Assustar Animais (-0 pto)', code: 'Assustar Animais'},
            {name: 'Aura Má (-0 pto)', code: 'Aura Má'},
            {name: 'Bateria (-1 pto)', code: 'Bateria'},
            {name: 'Beijo (-2 pto)', code: 'Beijo'},
            {name: 'Carniçal (+1 pto)', code: 'Carniçal'},
            {name: 'Cegueira (-3 pto)', code: 'Cegueira'},
            {name: 'Código de Honra: Area (-1 pto)', code: 'Código de Honra: Area'},
            {name: 'Código de Honra: Assimov (-1 pto)', code: 'Código de Honra: Assimov'},
            {name: 'Código de Honra: Caçador (-1 pto)', code: 'Código de Honra: Caçador'},
            {name: 'Código de Honra: Cavaleiros (-1 pto)', code: 'Código de Honra: Cavaleiros'},
            {name: 'Código de Honra: Combate (-1 pto)', code: 'Código de Honra: Combate'},
            {name: 'Código de Honra: Criador (-1 pto)', code: 'Código de Honra: Criador	'},
            {name: 'Código de Honra: Ecologia (-1 pto)', code: 'Código de Honra: Ecologia'},
            {name: 'Código de Honra: Derrota (-1 pto)', code: 'Código de Honra: Derrota'},
            {name: 'Código de Honra: Guardião (-1 pto)', code: 'Código de Honra: Guardião'},
            {name: 'Código de Honra: Heróis (-1 pto)', code: 'Código de Honra: Heróis'},
            {name: 'Código de Honra: Honestidade (-1 pto)', code: 'Código de Honra: Honestidade'},
            {name: 'Código de Honra: Pacifismo (-1 pto)', code: 'Código de Honra: Pacifismo'},
            {name: 'Código de Honra: Piratas (-1 pto)', code: 'Código de Honra: Piratas'},
            {name: 'Código de Honra: Retribuição (-1 pto)', code: 'Código de Honra: Retribuição'},
            {name: 'Código de Honra: Sacerdote (-1 pto)', code: 'Código de Honra: Sacerdote'},
            {name: 'Código de Honra: Todos (-4 pto)', code: 'Código de Honra: Todos'},
            {name: 'Convite (-1 pto)', code: 'Convite'},
            {name: 'Criança (-2 pto)', code: 'Criança'},
            {name: 'Curto Circuito (-2 pto)', code: 'Curto Circuito'},
            {name: 'Densidade Ampliada (-1 pto)', code: 'Densidade Ampliada'},
            {name: 'Dependência (-2 pto)', code: 'Dependência'},
            {name: 'Descontrole (-2 pto)', code: 'Descontrole'},
            {name: 'Devoção (-2 pto)', code: 'Devoção'},
            {name: 'Efeito Colateral (-1 pto)', code: 'Efeito Colateral'},
            {name: 'Esqueleto* (-2 pto)', code: 'Esqueleto*'},
            {name: 'Fetiche (-1 pto)', code: 'Fetiche'},
            {name: 'Fraqueza (-2 ou -3 pto)', code: 'Anão'},
            {name: 'Furia (-1 pto)', code: 'Furia'},
            {name: 'Goblin* (-2 pto)', code: 'Goblin*'},
            {name: 'Grilhão (-1 pto)', code: 'Grilhão'},
            {name: 'Guia (-1 pto)', code: 'Guia'},
            {name: 'Inculto (-1 pto)', code: 'Inculto'},
            {name: 'Inimigo (-1 ou -2 pto)', code: 'Inimigo'},
            {name: 'Insano: Cléptomaniaco (-1 pto)', code: 'Insano: Cléptomaniaco'},
            {name: 'Insano: Compulsivo (-1 pto)', code: 'Insano: Compulsivo'},
            {name: 'Insano: Covardia (-2 pto)', code: 'Insano: Covardia'},
            {name: 'Insano: Demente (-1 pto)', code: 'Insano: Demente'},
            {name: 'Insano: Depressivo (-2 pto)', code: 'Insano: Depressivo'},
            {name: 'Insano: Dupla Personalidade (0 pto)', code: 'Insano: Dupla Personalidade'},
            {name: 'Insano: Distraido (0 pto)', code: 'Insano: Distraido'},
            {name: 'Insano: Fantasia (-1 pto)', code: 'Insano: Fantasia'},
            {name: 'Insano: Fobia (-1 a -3 pto)', code: 'Insano: Fobia'},
            {name: 'Insano: Furioso (-1 pto)', code: 'Insano: Furioso'},
            {name: 'Insano: Ganância (-1 pto)', code: 'Insano: Ganância'},
            {name: 'Insano: Histérico (-2 pto)', code: 'Insano: Histérico'},
            {name: 'Insano: Homicida (-2 pto)', code: 'Insano: Homicida'},
            {name: 'Insano: Luxuria (-1 pto)', code: 'Insano: Luxuria'},
            {name: 'Insano: Megalomaniaco (-1 pto)', code: 'Insano: Megalomaniaco'},
            {name: 'Insano: Mentiroso (-1 pto)', code: 'Insano: Mentiroso'},
            {name: 'Insano: Obsessivo(-2 pto)', code: 'Insano: Obsessivo'},
            {name: 'Insano: Paranóico (-1 pto)', code: 'Insano: Paranóico'},
            {name: 'Insano: Sonambulo (-1 pto)', code: 'Insano: Sonambulo'},
            {name: 'Insano: Suicida (0 pto)', code: 'Insano: Suicida'},
            {name: 'Insano: Vaidade (-1 pto)', code: 'Insano: Vaidade'},
            {name: 'Interferência (-1 pto)', code: 'Interferência'},
            {name: 'Má Fama (-1 pto)', code: 'Má Fama'},
            {name: 'Mácula do Apodrecimento (-1 pto)', code: 'Mácula do Apodrecimento'},
            {name: 'Maldição: suave	 (-1 pto)', code: 'Maldição: suave'},
            {name: 'Maldição: grave (-2 pto)', code: 'Maldição: grave'},
            {name: 'Manutenção (-1 pto)', code: 'Manutenção'},
            {name: 'Meio - orc* (-1 pto)', code: 'Meio - orc*'},
            {name: 'Modelo Especial (-1 pto)', code: 'Modelo Especial'},
            {name: 'Monstruoso (-1 pto)', code: 'Monstruoso'},
            {name: 'Mudo (-2 pto)', code: 'Mudo'},
            {name: 'Morto - vivo* (-2 pto)', code: 'Morto - vivo*'},
            {name: 'Munição Limitada (-1 pto)', code: 'Munição Limitada'},
            {name: 'Ponto Fraco (-1 pto)', code: 'Ponto Fraco'},
            {name: 'Pontos de Morte (-1 pto)', code: 'Pontos de Morte'},
            {name: 'Prata ou Ferro Frio(-1 pto)', code: 'Prata ou Ferro Frio'},
            {name: 'Premonição (-1 ou -3 pto)', code: 'Anão'},
            {name: 'Procurado (-1 pto)', code: 'Procurado'},
            {name: 'Protegido Indefeso (-1 pto)', code: 'Protegido Indefeso'},
            {name: 'Psicopatia (-5 pto)', code: 'Psicopatia'},
            {name: 'Recarga (-1 ou -2 pto)', code: 'Recarga'},
            {name: 'Reflexo Sombrio (-1 pto)', code: 'Reflexo Sombrio'},
            {name: 'Restrição a magia: Incomum (-1 pto)', code: 'Restrição a magia: Incomum'},
            {name: 'Restrição a magia: Comum (-2 pto)', code: 'Restrição a magia: Comum'},
            {name: 'Restrição a magia: Muito Comum (-3 pto)', code: 'Restrição a magia: Muito Comum'},
            {name: 'Restrição a superpoder: Incomum (-1 pto)', code: 'Restrição a superpoder: Incomum'},
            {name: 'Restrição a superpoder: Comum (-2 pto)', code: 'Restrição a superpoder: Comum'},
            {name: 'Restrição a superpoder: Muito Comum (-3 pto)', code: 'Restrição a superpoder: Muito Comum'},
            {name: 'Segredo (-1 pto)', code: 'Segredo'},
            {name: 'Sem Iniciativa (-1 pto)', code: 'Sem Iniciativa'},
            {name: 'Sem Reflexo (-1 pto)', code: 'Sem Reflexo'},
            {name: 'Sensibilidade à Luz (-1 pto)', code: 'Sensibilidade à Luz'},
            {name: 'Sensibilidade ao Sol (-1 pto)', code: 'Sensibilidade ao Sol'},
            {name: 'Símbolos Sagrados (-2 pto)', code: 'Símbolos Sagrados'},
            {name: 'Sinal (-1 pto)', code: 'Sinal'},
            {name: 'Sucetivel a Hipnose (-1 pto)', code: 'Sucetivel a Hipnose'},
            {name: 'Sucetivel a Venenos (-2 pto)', code: 'Sucetivel a Venenos'},
            {name: 'Surdo (-3 pto)', code: 'Surdo'},
            {name: 'Terremoto Desfavoravel (-1 pto)', code: 'Terremoto Desfavoravel'},
            {name: 'Torpor (-1 ou -2 pto)', code: 'Torpor'},
            {name: 'Traição (-1 pto)', code: 'Traição'},
            {name: 'Transformação Descontrolada (-1 pto)', code: 'Transformação Descontrolada'},
            {name: 'Tumba (-1 pto)', code: 'Tumba'},
            {name: 'Vinculo (-1 pto)', code: 'Vinculo'},
            {name: 'Visão deficiente (0 ou -1 pto)', code: 'Visão deficiente'},
            {name: 'Vampiro* (-2 pto)', code: 'Vampiro*'},
            {name: 'Vulnerabilidade poder de fogo (-3 pto)', code: 'Vulnerabilidade poder de fogo'},
            {name: 'Vulnerabilidade força (-2 pto)', code: 'Vulnerabilidade força'},
            {name: 'Vulnerabilidade magia (-2 pto)', code: 'Vulnerabilidade magia'},
            {name: 'Vulnerabilidade corte (-1 pto)', code: 'Vulnerabilidade corte'},
            {name: 'Vulnerabilidade perfuração (-1 pto)', code: 'Vulnerabilidade perfuração'},
            {name: 'Vulnerabilidade contusão (-1 pto)', code: 'Vulnerabilidade contusão'},
            {name: 'Vulnerabilidade explosão (-1 pto)', code: 'Vulnerabilidade explosão'},
            {name: 'Vulnerabilidade calor/fogo (-1 pto)', code: 'Vulnerabilidade calor/fogo'},
            {name: 'Vulnerabilidade frio/gelo (-1 pto)', code: 'Vulnerabilidade frio/gelo'},
            {name: 'Vulnerabilidade luz (-1 pto)', code: 'Vulnerabilidade luz'},
            {name: 'Vulnerabilidade eletricidade (-1 pto)', code: 'Vulnerabilidade eletricidade'},
            {name: 'Vulnerabilidade vento/som (-1 pto)', code: 'AnãVulnerabilidade vento/som'},
            {name: 'Vulnerabilidade quimico (-1 pto)', code: 'Vulnerabilidade quimico'},
            {name: 'Vulnerabilidade agua (-1 pto)', code: 'Vulnerabilidade agua'},
            {name: 'Vulnerabilidade acido (-1 pto)', code: 'Vulnerabilidade acido'},
            {name: 'Vulnerabilidade venenos (-1 pto)', code: 'Vulnerabilidade venenos'},
            {name: 'Zumbi* (-2 pto)', code: 'Zumbi*'}

        ];

        return (
            <div>
                
                <div className="content-section implementation">
                    
                    <Dropdown value={this.props.valores} options={vantagens} onChange={this.props.mudanca} placeholder="Vantagens" optionLabel="name" filter={true} />
                    <br />
                    <Dropdown value={this.state.sas} options={vantagens} onChange={this.props.mudanca} placeholder="Vantagens" optionLabel="name" filter={true} />

                   
                </div>
            </div>
        );
    }
}
